### ISSUE TITLE
Multiple href to same page

### ISSUE THREAD

**Issue by olestole** [itdagene-ntnu/itdagene-webapp#110]
Wouldn't it be more natural if the "Sommerjobb" link has href to `/jobb` instead of `/program`?
https://github.com/itdagene-ntnu/itdagene-webapp/blob/96cebc51edf74e38d40628f055f4d5983383183c/components/CompactProgram/index.js#L59-L63

"Kurs" and "Les mer" already have href to `/program`, as well.

**Comment by SmithPeder** [comment]
Ohh, ups, that must be a typo 🙃
