### ISSUE TITLE
Serif font is used on browsers other than chrome

### ISSUE THREAD

**Issue by theodorsm** [itdagene-ntnu/itdagene-webapp#591]
![image](https://user-images.githubusercontent.com/55149662/110324933-f1d78000-8016-11eb-80b1-75315073bc34.png)
The left one is firefox, the right one is chromium.

**Comment by LudvigHz** [comment]
https://rawgit.com/
This has been deprecated for a looong time :upside_down_face: 

I suggest using the font off of google fonts https://fonts.google.com/specimen/Raleway
and using the new CSS option to fix the numbers (the reason we used that patched font from rawgit):
```css
font-variant-numeric: lining-nums;
```
